name: Release docs test

on:
  pull_request:

permissions:
  contents: write

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install deps
        run: pnpm install
      - name: Build
        run: pnpm docs:build -d docs_dist
